Entrar/dejar un rol
darkaqua/darkbot pull request #22
Opened 2017-03-12 23:00 UTC by TheCreativeGod

Permite a un usuario entrar o dejar ciertos roles
Uso: `!rol join/leave [name]`
Ejemplo: `!rol join [coder]`

2017-03-13 10:00 UTC, mcmacker4 requested changes
En cuanto arregles lo que te he dicho, lo pruebo en mi servidor y si funciona hago el merge.

2017-03-13 10:00 UTC, mcmacker4 commented on bot/commands/cm_rol.js
> +  })();
Aqui no necesitas un closure aqui, no hay ninguna variable para esconder.
```js
let rol = args[2] ? message.guild.roles.findKey("name", roleName) : "";
```

2017-03-13 10:00 UTC, mcmacker4 commented on bot/commands/cm_rol.js
> +}
Que ha pasado con las tabulaciones?? :fearful:
La mayoria de editores de codigo tienen un atajo para arreglar el formato del texto automaticamente. Usalo pls.

2017-03-13 10:00 UTC, mcmacker4 commented on bot/commands/cm_rol.js
> +const special = ["[admin]", "[sub-admin]", "[project]", "[bot]", "[darkbot coder]", "tercer componente de Daft Punk", "[salt]", "[helper]"];
Maybe añadir `[salt]` aqui? Se le asigna a los jugadores del LoL automaticamente.

2017-03-13 15:11 UTC, mcmacker4 commented on bot/commands/cm_rol.js
> +const special = ["[admin]", "[sub-admin]", "[project]", "[bot]", "[darkbot coder]", "tercer componente de Daft Punk", "[salt]", "[helper]"];
Y ahora que lo pienso, igual esto debería ir al `config.json` para acceder desde `global.config`, y no deberían ser los protegidos, sino los que se pueden usar.

2017-03-13 18:37 UTC, TheCreativeGod commented on bot/commands/cm_rol.js
> +  })();
Necesito `roleName` para probar que esté en la lista, `rol` me da la ID o en ese caso tendría que poner ID's en lugar de nombres en la lista de roles(?).
Si hago
```JS
let rol = args[2] ? message.guild.roles.findKey("name", roleName) : "";
```
si el rol tiene espacios habrá u problema por ahí... por ahora no habría problema, pero si en un futuro deciden crear un rol con espacios si los habrá.(?)

2017-03-13 18:40 UTC, TheCreativeGod commented on bot/commands/cm_rol.js
> +  })();
Wait... what? me dió una embolía... no sé que leí la 1ra vez...

2017-03-13 18:49 UTC, mcmacker4 commented on bot/commands/cm_rol.js
> +  })();
No he dicho nada de roleName, lo que has hecho aquí de `(() => { return cosa; })()` es un closure, se suele usar para esconder variables, pero ahí no es necesario porque no hay ninguna variable a esconder.

Sobre lo de los espacios, realmente no es necesario escribir el rol con barras bajas porque el argumento de role es el ultimo. En un comando `!role join un rol con espacios` sabes que el primer argumento es `role` el segundo sera `join` o `leave` y a partir de ahí, podrías juntar el resto de argumentos (`un rol con espacios`) en uno solo usando espacios como separador, et voilà, tienes un bonito rol con espacios.

2017-03-19 09:39 UTC, pagoru commented on bot/commands/cm_rol.js
> +const special = ["[admin]", "[sub-admin]", "[project]", "[bot]", "[darkbot coder]", "tercer componente de Daft Punk", "[salt]", "[helper]"];
¿Mejor como archvio de constantes dentro del proyecto, junto a la id de las salas?

2017-03-23 00:05 UTC, TheCreativeGod commented on bot/commands/cm_rol.js
> +			if (rol && global.config.roles.includes(roleName)) {
Se necesita agregar
```JSON
"roles": ["lista", "de", "roles"]
```
A `config.json`

2017-03-23 00:20 UTC, pagoru commented on bot/commands/cm_rol.js
> +			if (rol && global.config.roles.includes(roleName)) {
Cambia el `README.md` !!

2017-03-23 00:31 UTC, TheCreativeGod commented on bot/commands/cm_rol.js
> +			if (rol && global.config.roles.includes(roleName)) {
Hecho borquecho.

2017-03-29 13:42 UTC, pagoru approved these changes

2017-03-29 13:54 UTC, mcmacker4 requested changes
Solo un cambio mas y te dejo en paz (sorry).

2017-03-29 13:54 UTC, mcmacker4 commented on bot/commands/cm_rol.js
> +					message.author.sendMessage(`Te has unido a \`${roleName}\``);
`member.addRole(rol)` devuelve una Promise que podria lanzar un error. Si salta error saltara el maldito `Unhandled Promise Rejection Error` que no te dice donde ha saltado el error. A parte, si salta el error aun asi se enviara el mensaje de `Te has unido` cuando realmente no ha ocurrido. Yo lo cambiaria por esto (y en el leave tambien):

```js
message.member.addRole(rol).then(member =>
    message.author.sendMessage(`Te has unido a \`${roleName}\``)
).catch(err => {
    message.author.sendMessage("Se ha producido un error al unirte al rol.");
    console.log(err.message);
});
```

2017-03-29 14:02 UTC, mcmacker4 approved these changes

2017-04-05 02:00 UTC, merged

2017-04-10 15:53 UTC, pagoru commented
Fixed darkaqua/old_darkbot#69